SCHEMA_METADATA = {
    "demographics.customer_id": {
        "description": "Unique identifier for each customer"
    },
    "demographics.age": {
        "description": "Customer age in years"
    },
    "demographics.gender": {
        "description": "Customer gender"
    },
    "demographics.married": {
        "description": "Whether the customer is married"
    },
    "demographics.dependents": {
        "description": "Whether the customer has dependents"
    },

    "services.customer_id": {
        "description": "Unique customer identifier"
    },
    "services.tenure_in_months": {
        "description": "How long the customer has been with the telecom company, measured in months"
    },
    "services.monthly_charge": {
        "description": "Amount the customer is charged per month for telecom services"
    },
    "services.total_charges": {
        "description": "Total accumulated service charges for the customer"
    },
    "services.total_revenue": {
        "description": "Total revenue generated by the customer"
    },
    "services.avg_monthly_gb_download": {
        "description": "Average amount of internet data downloaded by the customer per month, measured in GB"
    },
    "services.internet_type": {
        "description": "Type of internet service used by the customer"
    },
    "services.internet_service": {
        "description": "Whether the customer has internet service, recorded as Yes or No"
    },
    "services.contract": {
        "description": "Customer contract type"
    },
    "services.payment_method": {
        "description": "Payment method used by the customer"
    },

    "status.customer_id": {
        "description": "Unique customer identifier"
    },
    "status.customer_status": {
        "description": "Current customer status such as Stayed, Joined, or Churned"
    },
    "status.churn_value": {
        "description": "Binary historical churn indicator where 1 means the customer churned and 0 means the customer did not churn"
    },
    "status.churn_score": {
        "description": "Numeric churn score associated with the customer"
    },
    "status.satisfaction_score": {
        "description": "Customer satisfaction score"
    },
    "status.cltv": {
        "description": "Customer Lifetime Value"
    },

    "location.customer_id": {
        "description": "Unique customer identifier"
    },
    "location.city": {
        "description": "City where the customer is located"
    },
    "location.zip_code": {
        "description": "Customer ZIP code"
    },

    "population.zip_code": {
        "description": "ZIP code"
    },
    "population.population": {
        "description": "Population of the corresponding ZIP code"
    }
}
