import re


# Lightweight inflection normalization for schema concepts.  These are
# domain words, not complete user questions, so equivalent wording reaches
# both deterministic parsing and semantic retrieval consistently.
DOMAIN_INFLECTIONS = {
    "accounts": "account",
    "bills": "bill",
    "charges": "charge",
    "cities": "city",
    "clients": "client",
    "contracts": "contract",
    "customers": "customer",
    "methods": "method",
    "revenues": "revenue",
    "subscribers": "subscriber",
    "types": "type",
    "users": "user",
}


def normalize_schema_language(text: str) -> str:
    """Normalize common schema-concept inflections without changing intent."""

    normalized = " ".join(text.lower().replace("-", " ").split())
    for plural, singular in DOMAIN_INFLECTIONS.items():
        normalized = re.sub(
            rf"\b{re.escape(plural)}\b",
            singular,
            normalized,
        )
    return normalized


SCHEMA_METADATA = {
    "demographics.customer_id": {
        "description": "Unique identifier for each customer"
    },
    "demographics.age": {
        "description": "Customer age in years",
        "data_type": "integer",
        "aliases": ["age", "years old", "customer age"],
    },
    "demographics.gender": {
        "description": "Customer gender"
    },
    "demographics.married": {
        "description": "Whether the customer is married"
    },
    "demographics.dependents": {
        "description": "Whether the customer has dependents"
    },

    "services.customer_id": {
        "description": "Unique customer identifier"
    },
    "services.tenure_in_months": {
        "description": "How long the customer has been with the telecom company, measured in months",
        "data_type": "integer",
        "aliases": ["tenure", "months with us", "customer duration"],
    },
    "services.monthly_charge": {
        "description": "Amount the customer is charged per month for telecom services",
        "data_type": "number",
        "aliases": ["monthly charge", "monthly charges", "monthly bill", "monthly bills"],
    },
    "services.total_charges": {
        "description": "Total accumulated service charges for the customer",
        "data_type": "number",
        "aliases": ["total charge", "total charges", "accumulated charges"],
    },
    "services.total_revenue": {
        "description": "Total revenue generated by the customer",
        "data_type": "number",
        "aliases": ["total revenue", "total revenues", "revenue generated"],
    },
    "services.avg_monthly_gb_download": {
        "description": "Average amount of internet data downloaded by the customer per month, measured in GB",
        "data_type": "number",
        "aliases": ["monthly data download", "average monthly GB download"],
    },
    "services.internet_type": {
        "description": "Type of internet service used by the customer"
    },
    "services.internet_service": {
        "description": "Whether the customer has internet service, recorded as Yes or No"
    },
    "services.contract": {
        "description": "Customer contract type"
    },
    "services.payment_method": {
        "description": "Payment method used by the customer"
    },

    "status.customer_id": {
        "description": "Unique customer identifier"
    },
    "status.customer_status": {
        "description": "Current customer status such as Stayed, Joined, or Churned"
    },
    "status.churn_value": {
        "description": "Binary historical churn indicator where 1 means the customer churned and 0 means the customer did not churn",
        "data_type": "integer",
    },
    "status.churn_score": {
        "description": "Numeric churn score associated with the customer",
        "data_type": "integer",
    },
    "status.satisfaction_score": {
        "description": "Customer satisfaction score",
        "data_type": "integer",
    },
    "status.cltv": {
        "description": "Customer Lifetime Value",
        "data_type": "integer",
    },

    "location.customer_id": {
        "description": "Unique customer identifier"
    },
    "location.city": {
        "description": "City where the customer is located"
    },
    "location.zip_code": {
        "description": "Customer ZIP code",
        "data_type": "integer",
    },

    "population.zip_code": {
        "description": "ZIP code",
        "data_type": "integer",
    },
    "population.population": {
        "description": "Population of the corresponding ZIP code",
        "data_type": "integer",
    }
}
